# Generated by Django 4.2.27 on 2025-12-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrajectoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, max_length=9, verbose_name='MMSI')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': '轨迹点',
                'verbose_name_plural': '轨迹点列表',
                'ordering': ['timestamp'],
            },
        ),
    ]
