# Generated by Django 4.2.27 on 2025-12-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleDraggingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.CharField(db_index=True, max_length=20, verbose_name='MMSI')),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('lng', models.FloatField(verbose_name='经度')),
                ('sog', models.FloatField(verbose_name='航速(SOG)')),
                ('cog', models.FloatField(verbose_name='航向(COG)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '双拖轨迹点',
                'verbose_name_plural': '双拖轨迹点列表',
                'ordering': ['-timestamp'],
            },
        ),
    ]
