# Generated by Django 4.2.27 on 2026-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IllegalBerthingPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chinese_mmsi",
                    models.CharField(
                        db_index=True, max_length=9, verbose_name="中国籍船舶 MMSI"
                    ),
                ),
                (
                    "foreign_mmsi",
                    models.CharField(
                        db_index=True, max_length=9, verbose_name="外籍船舶 MMSI"
                    ),
                ),
                (
                    "permit_number",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="许可编号"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(blank=True, null=True, verbose_name="有效期开始"),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, null=True, verbose_name="有效期结束"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("notes", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "船舶搭靠许可",
                "verbose_name_plural": "船舶搭靠许可",
                "ordering": ["chinese_mmsi", "foreign_mmsi", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["chinese_mmsi", "foreign_mmsi", "is_active"],
                        name="berth_permit_pair_idx",
                    )
                ],
            },
        ),
    ]
