# Generated by Django 4.2.27 on 2025-12-18 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AbnormalParking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parkingbuffer",
            options={"ordering": ["timestamp"], "verbose_name": "停泊检测缓冲点"},
        ),
    ]
