# Generated by Django 4.2.27 on 2026-03-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HighSpeedPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(db_index=True, max_length=20, verbose_name="MMSI"),
                ),
                ("speed", models.FloatField(verbose_name="航速(SOG)")),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="时间戳")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "低速检测轨迹点",
                "verbose_name_plural": "低速检测轨迹点列表",
                "ordering": ["-timestamp"],
            },
        ),
    ]
