# Generated by Django 4.2.27 on 2025-12-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StayingBuffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(db_index=True, max_length=50, verbose_name="MMSI"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="船名"
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("speed", models.FloatField(default=0.0, verbose_name="航速")),
                ("timestamp", models.DateTimeField(db_index=True, verbose_name="上报时间")),
            ],
            options={
                "verbose_name": "驻留检测缓冲点",
                "ordering": ["timestamp"],
            },
        ),
    ]
