# Generated by Django 4.2.27 on 2025-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(max_length=9, unique=True, verbose_name="MMSI"),
                ),
                ("shipName", models.CharField(max_length=32, verbose_name="船舶名称")),
                ("shipType", models.CharField(max_length=32, verbose_name="船舶类型")),
                ("length", models.FloatField(verbose_name="船长（米）")),
                ("width", models.FloatField(verbose_name="船宽（米）")),
            ],
            options={
                "verbose_name": "船舶",
                "verbose_name_plural": "船舶列表",
                "ordering": ["mmsi"],
            },
        ),
    ]
