# Generated by Django 4.2.27 on 2025-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(max_length=50, verbose_name="目标ID/MMSI"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                (
                    "is_abnormal",
                    models.BooleanField(default=False, verbose_name="是否存在异常徘徊"),
                ),
                (
                    "abnormal_count",
                    models.IntegerField(default=0, verbose_name="异常段数量"),
                ),
                ("details", models.TextField(blank=True, verbose_name="详细结果JSON")),
            ],
        ),
        migrations.CreateModel(
            name="MonitorRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="区域名称")),
                ("min_lon", models.FloatField(verbose_name="最小经度")),
                ("max_lon", models.FloatField(verbose_name="最大经度")),
                ("min_lat", models.FloatField(verbose_name="最小纬度")),
                ("max_lat", models.FloatField(verbose_name="最大纬度")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
            ],
        ),
    ]
