"""
Django settings for WanAna02702 project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*r)vh3k)2a_kd2jwt9ur87o&g)mbf=v#1ds8$e85i*f0p(-t6s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.150.50.125', 'localhost', '127.0.0.1', '10.150.50.74']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "AISData",
    "home",
    "AISRadar",
    "VISAIS",
    "UAVVISAIS",
    "VISINF",
    "SARAIS",
    "AbnormalParking",
    "AbnormalTransfer",
    "AbnormalWandering",
    "BlackList",
    "Collision",
    "Deviation",
    "DoubleDragging",
    "CrossingBoundary",
    "HighSpeedBoat",
    "IllegalAnchored",
    "IllegalBerthing",
    "IllegalFarming",
    "IllegalFishing",
    "IllegalPolutionDis",
    "IllegalSandMining",
    "IllegalStaying",
    "LowSpeed",
    "Overload",
    "Smuggling",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "WanAna02702.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "WanAna02702.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 指定数据库引擎
        'NAME': 'warana',                       # 数据库名称
        'USER': 'root',                         # 数据库用户名
        'PASSWORD': '12345678',                 # 数据库密码
        'HOST': 'localhost',                    # 数据库主机地址
        'PORT': '3306',                         # 数据库端口，默认为3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 登录成功后的跳转页面
LOGIN_REDIRECT_URL = '/home/'

# 2. 指定 ASGI 应用程序
ASGI_APPLICATION = 'WanAna02702.routing.application'

# 3. 配置 Channel Layer (必需，用于在不同消费者之间或外部发送消息)
# 使用 In-memory（开发环境）或 Redis（生产环境推荐）
CHANNEL_LAYERS = {
    'default': {
        # 'BACKEND': 'channels.layers.InMemoryChannelLayer' 
        # 生产环境请使用：
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': { 'hosts': [('127.0.0.1', 6379)], }
    },
}

# Redis Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # 请确保地址和端口与你本地 Redis 一致
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 设置缓存过期时间（可选，默认 5 分钟）
CACHE_TTL = 60 * 5