"""
Django settings for WanAna02702 project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*r)vh3k)2a_kd2jwt9ur87o&g)mbf=v#1ds8$e85i*f0p(-t6s"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.150.50.125', 'localhost', '127.0.0.1', '10.150.50.74', '10.93.98.8', '0.0.0.0']
ALLOWED_HOSTS.extend(
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
)

# Both launch profiles expose the same browser and WebSocket URLs. The
# process-level setting selects which isolated AIS state backs /ws/ais/.
AIS_DEFAULT_SOURCE = os.environ.get(
    "AIS_DEFAULT_SOURCE",
    "operational",
).strip().lower()
if AIS_DEFAULT_SOURCE not in {"operational", "predict"}:
    raise ValueError(
        "AIS_DEFAULT_SOURCE must be either operational or predict"
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "AISData",
    "home",
    "AISRadar",
    "CloseAIS",
    "VISAIS",
    "UAVVISAIS",
    "VISINF",
    "SARAIS",
    "AbnormalParking",
    "AbnormalTransfer",
    "AbnormalWandering",
    "BlackList",
    "Collision",
    "Deviation",
    "DoubleDragging",
    "CrossingBoundary",
    "HighSpeedBoat",
    "IllegalAnchored",
    "IllegalBerthing",
    "IllegalFarming",
    "IllegalFishing",
    "IllegalPolutionDis",
    "IllegalSandMining",
    "IllegalStaying",
    "LowSpeed",
    "Overload",
    "Smuggling",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "WanAna02702.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "WanAna02702.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 指定数据库引擎
        'NAME': 'warana',                       # 数据库名称
        'USER': 'root',                         # 数据库用户名
        'PASSWORD': '12345678',                 # 数据库密码
        'HOST': 'localhost',                    # 数据库主机地址
        'PORT': '3306',                         # 数据库端口，默认为3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 登录成功后的跳转页面
LOGIN_REDIRECT_URL = '/home/'

# 2. 指定 ASGI 应用程序
ASGI_APPLICATION = 'WanAna02702.routing.application'

# 3. 配置 Channel Layer (必需，用于在不同消费者之间或外部发送消息)
# 使用 In-memory（开发环境）或 Redis（生产环境推荐）
CHANNEL_LAYERS = {
    'default': {
        # 'BACKEND': 'channels.layers.InMemoryChannelLayer' 
        # 生产环境请使用：
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
            # AIS 快照只需要最新数据，不应为失联客户端积压大量旧帧。
            'capacity': 10,
            'expiry': 15,
        }
    },
}

# Redis Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # 请确保地址和端口与你本地 Redis 一致
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 设置缓存过期时间（可选，默认 5 分钟）
CACHE_TTL = 60 * 5

# Operational AIS positions are merged per MMSI.  A target is removed only
# after source event time has advanced beyond this retention window; static
# type 5/24 attributes are retained independently and joined onto positions.
AIS_LATEST_STATE_RETENTION_SECONDS = 15 * 60
AIS_STATIC_STATE_RETENTION_SECONDS = 7 * 24 * 60 * 60

# 为违法事件补存识别前的 AIS 航迹。历史按 MMSI 分开缓存，既能跨越
# ais_worker / detection_worker 进程读取，也避免一个全局大对象反复序列化。
AIS_TRAJECTORY_HISTORY_WINDOW_SECONDS = 30 * 60
# 共享行为层需要覆盖异常停泊/非法驻留的最长分析窗口；普通轨迹查询仍
# 默认返回30分钟，避免其他模型无意扩大数据量。
AIS_TRAJECTORY_HISTORY_RETENTION_SECONDS = 120 * 60
AIS_TRAJECTORY_HISTORY_CACHE_TTL = 2 * 60 * 60
AIS_TRAJECTORY_HISTORY_MAX_POINTS_PER_SHIP = 2000
AIS_TRAJECTORY_MIN_DISTANCE_METERS = 3.0
# 即使船舶位置变化不足最小距离，也按固定时间间隔保留一个点，
# 用于证明抛锚、驻留等静止状态在时间上的连续性。
AIS_TRAJECTORY_MAX_INTERVAL_SECONDS = 3 * 60

# 靠泊、锚泊和普通驻留共用的物理行为识别层。各预警模型只在行为结果
# 之上检查各自的区域、许可和持续时间，不再重复分析同一段低速轨迹。
LOW_SPEED_BEHAVIOR_RECOGNITION = {
    "history_window_seconds": 120 * 60,
    "stationary_speed_knots": 0.5,
    "exit_speed_knots": 1.0,
    # 共享层保留三类行为中最大的连续观测间隔；更严格的区域持续时间
    # 间隔由各预警消费者分别校验。
    "max_gap_seconds": 20 * 60,
    "max_episode_distance_metres": 250,
    "stationary_radius_metres": 250,
    "min_points": 3,
    "min_heading_observations": 2,
    "max_berthing_heading_degrees": 25,
    "anchor_swing_heading_degrees": 45,
    "min_anchor_status_ratio": 0.6,
    "min_moored_status_ratio": 0.6,
    "moored_underway_min_speed_knots": 1.0,
    "moored_underway_min_path_distance_metres": 100,
    "moored_underway_min_duration_seconds": 300,
    "moored_underway_min_points": 3,
}
LOW_SPEED_BEHAVIOR_CACHE_TTL = 2 * 60 * 60

# 模拟摄像头实时推流。独立 management command 会持续循环 Data/Video
# 中的全部视频；是否存在前端观看者不会影响推流进程的启停。
CAMERA_STREAM = {
    "camera_key": "harbor-01",
    "video_directory": BASE_DIR / "Data" / "Video",
    # 0 表示保持每个源视频的原始帧率。
    "fps": 0,
    "max_width": 1280,
    # FFmpeg MJPEG 的 q:v 参数，数值越小质量越高、网络流量越大。
    "jpeg_quality": 5,
    # 留空时从系统 PATH 查找 ffmpeg。
    "ffmpeg_executable": "",
}

# 船舶超载视觉模型：订阅模拟摄像头流，但不会影响视频推流进程。
OVERLOAD_VIDEO_DETECTION = {
    "camera_key": "harbor-01",
    "weights": BASE_DIR / "Overload" / "weights" / "best.pt",
    "confidence": 0.5,
    # 原超载模型无检测框时，用通用船舶模型区分“无船”和“有船无载重线”。
    "vessel_weights": BASE_DIR / "Overload" / "weights" / "yolov8n.pt",
    "vessel_confidence": 0.25,
    # 视频保持源 FPS；模型按此上限抽帧推理，避免阻塞实时流。
    "inference_fps": 2,
    "confirmation_frames": 3,
    "device": "0",
}

# 异常停泊检测参数。
ABNORMAL_PARKING = {
    "analysis_window_minutes": 120,
    "retention_window_minutes": 240,
    "max_speed_knots": 0.5,
    "exit_speed_knots": 1.0,
    "distance_threshold_metres": 50,
    "position_exit_radius_metres": 100,
    "min_duration_minutes": 30,
    "min_points": 3,
    "max_gap_minutes": 20,
    "near_shore_distance_metres": 100,
    "max_heading_change_degrees": 25,
    "min_heading_observations": 2,
    "anchor_swing_heading_degrees": 45,
    "min_anchor_status_ratio": 0.6,
    "moored_underway_min_speed_knots": 1.0,
    "moored_underway_min_path_distance_metres": 100,
    "moored_underway_min_duration_minutes": 5,
    "moored_underway_min_points": 3,
    # 0 表示合法泊位不启用超时预警；有明确业务时限后可配置正数。
    "legal_max_duration_minutes": 0,
    "berthing_facility_areas": [],
    "legal_berthing_areas": [],
}

# 非法抛锚检测：港口/码头及合法锚地内不预警。
ILLEGAL_ANCHORED_DETECTION = {
    "max_speed_knots": 0.5,
    "min_duration_seconds": 300,
    "min_observations": 3,
    "max_drift_metres": 250,
    "history_window_seconds": 1800,
    "max_gap_seconds": 300,
    "min_heading_observations": 2,
    "anchor_swing_heading_degrees": 45,
    "min_anchor_status_ratio": 0.6,
}

# 非法驻留检测：只有在明确配置的禁停区域内持续低速停留才预警。
ILLEGAL_STAYING = {
    "analysis_window_minutes": 120,
    "retention_window_minutes": 240,
    "max_speed_knots": 0.5,
    "distance_threshold_metres": 50,
    "min_duration_minutes": 30,
    "min_points": 3,
    "min_heading_observations": 2,
    "anchor_swing_heading_degrees": 45,
    "min_anchor_status_ratio": 0.6,
    "maximum_gap_seconds": 180,
    "max_position_age_seconds": 120,
    "future_tolerance_seconds": 120,
    "event_retention_minutes": 60,
    "forbidden_areas": [
        {
            "name": "非法驻留监控区",
            "bounds": (
                113.6279434,
                22.1376273,
                113.7935190,
                22.2008193,
            ),
            "reason": "该区域禁止未经许可的长时间驻留",
        }
    ],
}

# 异常徘徊检测参数。启用的 MonitorRegion 数据库记录会覆盖默认监控区域。
ABNORMAL_WANDERING = {
    "analysis_window_minutes": 30,
    "retention_window_minutes": 60,
    "min_points": 10,
    "min_duration_minutes": 30,
    "max_range_metres": 3000,
    "min_path_distance_metres": 300,
    "min_leg_distance_metres": 20,
    "min_turn_angle_degrees": 30,
    "min_turn_count": 4,
    "max_displacement_ratio": 0.3,
    "min_revisit_ratio": 0.4,
    "grid_size_metres": 200,
    "revisit_enabled": True,
    "min_speed_knots": 0.5,
    "max_valid_speed_knots": 102.2,
    "max_jump_speed_knots": 80,
    "min_jump_distance_metres": 500,
    "min_turn_interval_seconds": 30,
    "max_gap_minutes": 5,
    # True=只检测异常徘徊监控区；False=对全部有效AIS轨迹运行模型。
    "monitored_only": True,
    "min_area_point_ratio": 0.5,
    "normal_anchorage_max_speed_knots": 0.5,
    "normal_anchorage_max_range_metres": 200,
    "normal_port_max_speed_knots": 3,
    "normal_port_max_range_metres": 1000,
    "normal_area_point_ratio": 0.8,
    # 可按 monitored_areas 相同的 bounds/vertices 格式配置施工区等合法作业区。
    "legal_operation_areas": [],
    "monitored_areas": [
        {
            "name": "异常徘徊监控区",
            "bounds": (
                113.6109833,
                22.1700302,
                113.7926567,
                22.2080471,
            ),
        },
    ],
}

# 船舶碰撞风险检测。DCPA/TCPA 阈值需要结合具体水域、船型及值班规则校准。
COLLISION_DETECTION = {
    "warning_tcpa_minutes": 15,
    "critical_tcpa_minutes": 5,
    "warning_dcpa_metres": 300,
    "critical_dcpa_metres": 150,
    "immediate_distance_metres": 100,
    "vessel_buffer_metres": 50,
    "minimum_relative_speed_mps": 0.2,
    "max_position_age_seconds": 120,
    "event_retention_minutes": 30,
}

# 双拖捕鱼预警参数。轨迹窗口必须覆盖最短持续时间。
DOUBLE_DRAGGING_DETECTION = {
    "analysis_window_minutes": 45,
    "retention_window_minutes": 60,
    "min_duration_minutes": 30,
    "min_aligned_points": 30,
    "alignment_tolerance_seconds": 45,
    "min_pair_distance_metres": 100,
    "max_pair_distance_metres": 2000,
    "candidate_distance_margin_metres": 500,
    "min_operating_speed_knots": 1,
    "max_operating_speed_knots": 8,
    "max_speed_difference_knots": 1.5,
    "max_course_difference_degrees": 20,
    "max_lateral_deviation_degrees": 30,
    "max_distance_std_metres": 250,
    "min_distance_ratio": 0.8,
    "min_course_ratio": 0.8,
    "min_lateral_ratio": 0.7,
    "min_speed_similarity_ratio": 0.8,
    "max_position_age_seconds": 120,
    "future_tolerance_seconds": 120,
    "event_retention_minutes": 30,
}

# 海上围栏跨界状态检测参数。
CROSSING_BOUNDARY_DETECTION = {
    "max_position_age_seconds": 120,
    "boundary_tolerance_metres": 10,
    "state_retention_hours": 24,
    # 越界是瞬时事件，保留一段时间供界面展示，避免下一帧立即覆盖。
    "event_retention_minutes": 30,
    "max_vertices": 500,
}

# 围栏和走私研判依赖完整前后轨迹，不能像持续状态模型一样合并AIS快照。
# 队列设置上限用于在检测进程异常时保护Redis。
TRAJECTORY_DETECTION_QUEUE_MAX_SNAPSHOTS = 500
DETECTION_INCREMENTAL_QUEUE_BATCH_SIZE = 100

# 海上走私风险研判。区域和航次许可由 Smuggling 数据表维护。
SMUGGLING_DETECTION = {
    "timezone": "Asia/Shanghai",
    "night_start_hour": 20,
    "night_end_hour": 6,
    "max_position_age_seconds": 120,
    "maximum_gap_seconds": 180,
    "origin_minimum_duration_seconds": 60,
    "origin_minimum_observations": 3,
    "maximum_voyage_hours": 12,
    "state_retention_hours": 24,
    "landing_speed_knots": 1.5,
    "landing_minimum_duration_seconds": 300,
    "landing_minimum_observations": 3,
    # 香港起航船舶进入距广东海岸线 5 公里范围后才进入近岸研判。
    "guangdong_nearshore_range_metres": 5000,
    # 全部已录入广东港口向外扩展 3 公里，命中即按正常港口航行排除。
    "guangdong_port_buffer_metres": 3000,
    "draught_change_metres": 0.5,
    "small_craft_length_metres": 50,
    "fast_craft_speed_knots": 15,
    "event_retention_minutes": 60,
    "minimum_risk_score": 40,
}

# 高速快艇预警：有效 AIS 航速持续大于 30 节，且不判断船型。
HIGH_SPEED_DETECTION = {
    "default_speed_limit_knots": 30,
    "minimum_duration_seconds": 300,
    "maximum_gap_seconds": 90,
    "analysis_window_minutes": 30,
    "retention_window_minutes": 60,
    "max_position_age_seconds": 120,
    "future_tolerance_seconds": 120,
    # AIS SOG 102.3 表示数据不可用，102.2 表示 102.2 节或更高。
    "max_valid_speed_knots": 102.2,
    "high_risk_excess_knots": 10,
    "event_retention_minutes": 30,
}

# 低速船舶预警：仅分析处于航行状态的船舶，zones 可配置分区最低航速。
LOW_SPEED_DETECTION = {
    "default_minimum_speed_knots": 1.5,
    "minimum_duration_seconds": 300,
    "minimum_observations": 5,
    "maximum_gap_seconds": 90,
    "analysis_window_minutes": 30,
    "retention_window_minutes": 60,
    "max_position_age_seconds": 120,
    "future_tolerance_seconds": 120,
    # AIS SOG 102.3 表示数据不可用。
    "max_valid_speed_knots": 102.2,
    "event_retention_minutes": 30,
    # 0=机动航行，15=未定义；缺失状态由 allow_missing_nav_status 控制。
    "eligible_nav_statuses": [0, 15],
    "allow_missing_nav_status": True,
    # nav_status 可能未及时更新；任何状态下连续5分钟处于50米范围内，
    # 且航速不超过0.5节时，均按锚泊/静止排除。
    "stationary_max_speed_knots": 0.5,
    "stationary_max_drift_metres": 50.0,
    "stationary_minimum_duration_seconds": 300,
    "monitored_only": False,
    "zones": [],
}

# AIS/Radar six-frame GMvA trajectory matching.  The model is loaded lazily on
# the first /AISRadar/match/ request and then reused by the Django process.
AIS_RADAR_INFERENCE = {
    "weights": BASE_DIR / "AISRadar" / "weights" / "mainline_seed42_epoch40.pth",
    "device": "auto",
    "window_size": 6,
    "geometry_weight": 0.01,
    "match_threshold": 0.0,
    "sinkhorn_iterations": 20,
    "expected_sha256": "94B1EECE8BA74C603CED986B027CF74753761929389B290AFB4FF2AD8FFA2D4E",
}

# 航道偏离：历史航迹仅覆盖琼州海峡知识库范围，区域外不执行检测。
DEVIATION_DETECTION = {
    "minimum_speed_knots": 2,
    "minimum_duration_seconds": 120,
    "minimum_observations": 5,
    "maximum_gap_seconds": 90,
    "minimum_displacement_metres": 500,
    "route_entry_distance_metres": 750,
    "deviation_distance_metres": 1500,
    "confirmation_observations": 3,
    "confirmation_duration_seconds": 60,
    "direction_tolerance_degrees": 45,
    "minimum_direction_coherence": 0.5,
    "coverage_margin_metres": 20000,
    "analysis_window_minutes": 30,
    "retention_window_minutes": 60,
    "max_position_age_seconds": 120,
    "future_tolerance_seconds": 120,
    "max_valid_speed_knots": 102.2,
    "state_retention_minutes": 30,
    "eligible_nav_statuses": [0, 15],
    "allow_missing_nav_status": True,
}

# 非法搭靠：仅检测中国籍船舶与外籍船舶持续低速、近距离搭靠。
# 有效许可记录通过 /IllegalBerthing/permits/ 维护。
ILLEGAL_BERTHING_DETECTION = {
    "chinese_mids": ["412", "413", "414"],
    "base_contact_distance_metres": 100,
    "maximum_contact_distance_metres": 250,
    "length_distance_factor": 0.5,
    "contact_buffer_metres": 25,
    "maximum_speed_knots": 2,
    "maximum_relative_speed_knots": 0.5,
    "minimum_duration_seconds": 300,
    "minimum_observations": 5,
    "maximum_gap_seconds": 90,
    "max_position_age_seconds": 120,
    # AIS SOG 102.3 表示数据不可用。
    "max_valid_speed_knots": 102.2,
    "state_retention_minutes": 30,
}

# 异常接驳：全国法规未规定统一作业时段和统一最高航速，具体限制来自
# 主管机关批准的作业方案/航行通告，并通过 AbnormalTransfer 作业计划维护。
ABNORMAL_TRANSFER_DETECTION = {
    "base_contact_distance_metres": 100,
    "maximum_contact_distance_metres": 250,
    "length_distance_factor": 0.5,
    "contact_buffer_metres": 25,
    "maximum_candidate_speed_knots": 20,
    "maximum_relative_speed_knots": 1,
    "maximum_course_difference_degrees": 30,
    "course_check_minimum_speed_knots": 1,
    "minimum_duration_seconds": 120,
    "minimum_observations": 3,
    "maximum_gap_seconds": 90,
    "max_position_age_seconds": 120,
    # AIS SOG 102.3 表示数据不可用。
    "max_valid_speed_knots": 102.2,
    "speed_tolerance_knots": 0.1,
    "state_retention_minutes": 30,
}
