# Generated by Django 4.2.27 on 2026-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransferOperationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vessel_a_mmsi",
                    models.CharField(
                        db_index=True, max_length=9, verbose_name="船舶 A MMSI"
                    ),
                ),
                (
                    "vessel_b_mmsi",
                    models.CharField(
                        db_index=True, max_length=9, verbose_name="船舶 B MMSI"
                    ),
                ),
                (
                    "operation_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="作业名称"
                    ),
                ),
                (
                    "approval_number",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="批准/通告编号"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(db_index=True, verbose_name="批准开始时间"),
                ),
                ("ends_at", models.DateTimeField(db_index=True, verbose_name="批准结束时间")),
                ("max_speed_knots", models.FloatField(verbose_name="最大规定航速（节）")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("notes", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "接驳作业计划",
                "verbose_name_plural": "接驳作业计划",
                "ordering": ["-starts_at", "vessel_a_mmsi", "vessel_b_mmsi"],
                "indexes": [
                    models.Index(
                        fields=["vessel_a_mmsi", "vessel_b_mmsi", "is_active"],
                        name="transfer_plan_pair_idx",
                    )
                ],
            },
        ),
    ]
